import { Snippet } from "./github";

/** Additional curated snippets to extend the daily pool beyond the base JSON file. */
export const extraDailySnippets: Snippet[] = [
  {
    lines: [
      "func (s *Server) handleRequest(w http.ResponseWriter, r *http.Request) {",
      "    ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)",
      "    defer cancel()",
      "    id := chi.URLParam(r, \"id\")",
      "    item, err := s.store.Get(ctx, id)",
      "    if err != nil {",
      "        http.Error(w, err.Error(), http.StatusNotFound)",
      "        return",
      "    }",
      "    w.Header().Set(\"Content-Type\", \"application/json\")",
      "    json.NewEncoder(w).Encode(item)",
      "}",
    ],
    language: "Go",
    repoName: "go-chi/chi",
    repoUrl: "https://github.com/go-chi/chi",
    repoDescription: "Lightweight, idiomatic and composable router for Go HTTP services.",
    framework: "Chi",
  },
  {
    lines: [
      "impl<T: Clone + Send + Sync> Cache<T> {",
      "    pub fn get_or_insert_with<F>(&self, key: &str, f: F) -> T",
      "    where",
      "        F: FnOnce() -> T,",
      "    {",
      "        let mut guard = self.inner.write().unwrap();",
      "        if let Some(v) = guard.get(key) {",
      "            return v.clone();",
      "        }",
      "        let value = f();",
      "        guard.insert(key.to_string(), value.clone());",
      "        value",
      "    }",
      "}",
    ],
    language: "Rust",
    repoName: "tokio-rs/tokio",
    repoUrl: "https://github.com/tokio-rs/tokio",
    repoDescription: "A runtime for writing reliable asynchronous applications with Rust.",
    framework: null,
  },
  {
    lines: [
      "@router.get(\"/users/{user_id}\")",
      "async def read_user(user_id: int, db: Session = Depends(get_db)):",
      "    user = db.query(User).filter(User.id == user_id).first()",
      "    if user is None:",
      "        raise HTTPException(status_code=404, detail=\"User not found\")",
      "    return user",
      "",
      "@router.post(\"/users/\")",
      "async def create_user(user: UserCreate, db: Session = Depends(get_db)):",
      "    db_user = User(**user.dict())",
      "    db.add(db_user)",
      "    db.commit()",
      "    db.refresh(db_user)",
      "    return db_user",
    ],
    language: "Python",
    repoName: "tiangolo/fastapi",
    repoUrl: "https://github.com/tiangolo/fastapi",
    repoDescription: "FastAPI framework, high performance, easy to learn, fast to code.",
    framework: "FastAPI",
  },
  {
    lines: [
      "export async function GET(request: Request) {",
      "  const { searchParams } = new URL(request.url);",
      "  const slug = searchParams.get('slug');",
      "  if (!slug) {",
      "    return NextResponse.json({ error: 'Missing slug' }, { status: 400 });",
      "  }",
      "  const post = await getPostBySlug(slug);",
      "  if (!post) {",
      "    return NextResponse.json({ error: 'Not found' }, { status: 404 });",
      "  }",
      "  return NextResponse.json(post);",
      "}",
    ],
    language: "TypeScript",
    repoName: "vercel/next.js",
    repoUrl: "https://github.com/vercel/next.js",
    repoDescription: "The React Framework for the Web.",
    framework: "Next.js",
  },
  {
    lines: [
      "class ApplicationController < ActionController::Base",
      "  before_action :authenticate_user!",
      "  def show",
      "    @resource = current_user.resources.find(params[:id])",
      "    render json: @resource, status: :ok",
      "  rescue ActiveRecord::RecordNotFound",
      "    render json: { error: 'not found' }, status: :not_found",
      "  end",
      "end",
    ],
    language: "Ruby",
    repoName: "rails/rails",
    repoUrl: "https://github.com/rails/rails",
    repoDescription: "Ruby on Rails is a web framework optimized for programmer happiness.",
    framework: "Rails",
  },
  {
    lines: [
      "@RestController",
      "@RequestMapping(\"/api/v1\")",
      "public class UserController {",
      "    private final UserService userService;",
      "    @GetMapping(\"/users/{id}\")",
      "    public ResponseEntity<UserDto> getUser(@PathVariable Long id) {",
      "        return userService.findById(id)",
      "            .map(ResponseEntity::ok)",
      "            .orElse(ResponseEntity.notFound().build());",
      "    }",
      "}",
    ],
    language: "Java",
    repoName: "spring-projects/spring-boot",
    repoUrl: "https://github.com/spring-projects/spring-boot",
    repoDescription: "Spring Boot helps you create stand-alone, production-grade Spring applications.",
    framework: "Spring",
  },
  {
    lines: [
      "public async Task<IActionResult> GetItem(int id)",
      "{",
      "    var item = await _repository.FindAsync(id);",
      "    if (item == null) return NotFound();",
      "    return Ok(item);",
      "}",
      "",
      "[HttpPost]",
      "public async Task<IActionResult> Create([FromBody] CreateItemDto dto)",
      "{",
      "    var entity = _mapper.Map<Item>(dto);",
      "    await _repository.AddAsync(entity);",
      "    return CreatedAtAction(nameof(GetItem), new { id = entity.Id }, entity);",
      "}",
    ],
    language: "C#",
    repoName: "dotnet/aspnetcore",
    repoUrl: "https://github.com/dotnet/aspnetcore",
    repoDescription: "ASP.NET Core is a cross-platform .NET framework for building web apps.",
    framework: null,
  },
  {
    lines: [
      "std::vector<int> merge_sorted(const std::vector<int>& a, const std::vector<int>& b) {",
      "    std::vector<int> out;",
      "    out.reserve(a.size() + b.size());",
      "    auto i = a.begin(), j = b.begin();",
      "    while (i != a.end() && j != b.end()) {",
      "        if (*i <= *j) out.push_back(*i++);",
      "        else out.push_back(*j++);",
      "    }",
      "    out.insert(out.end(), i, a.end());",
      "    out.insert(out.end(), j, b.end());",
      "    return out;",
      "}",
    ],
    language: "C++",
    repoName: "fmtlib/fmt",
    repoUrl: "https://github.com/fmtlib/fmt",
    repoDescription: "A modern formatting library for C++.",
    framework: null,
  },
  {
    lines: [
      "const debounce = (fn, ms) => {",
      "  let timer;",
      "  return (...args) => {",
      "    clearTimeout(timer);",
      "    timer = setTimeout(() => fn(...args), ms);",
      "  };",
      "};",
      "",
      "export function useSearch(query) {",
      "  const [results, setResults] = useState([]);",
      "  const fetchResults = useMemo(() => debounce(async (q) => {",
      "    const res = await api.search(q);",
      "    setResults(res.items);",
      "  }, 300), []);",
    ],
    language: "JavaScript",
    repoName: "facebook/react",
    repoUrl: "https://github.com/facebook/react",
    repoDescription: "The library for web and native user interfaces.",
    framework: "React",
  },
  {
    lines: [
      "type Handler func(http.ResponseWriter, *http.Request)",
      "",
      "func Logger(next Handler) Handler {",
      "    return func(w http.ResponseWriter, r *http.Request) {",
      "        start := time.Now()",
      "        next(w, r)",
      "        log.Printf(\"%s %s %v\", r.Method, r.URL.Path, time.Since(start))",
      "    }",
      "}",
    ],
    language: "Go",
    repoName: "golang/go",
    repoUrl: "https://github.com/golang/go",
    repoDescription: "The Go programming language.",
    framework: null,
  },
  {
    lines: [
      "def train_epoch(model, loader, optimizer, criterion):",
      "    model.train()",
      "    total_loss = 0.0",
      "    for batch in loader:",
      "        inputs, targets = batch",
      "        optimizer.zero_grad()",
      "        outputs = model(inputs)",
      "        loss = criterion(outputs, targets)",
      "        loss.backward()",
      "        optimizer.step()",
      "        total_loss += loss.item()",
      "    return total_loss / len(loader)",
    ],
    language: "Python",
    repoName: "pytorch/pytorch",
    repoUrl: "https://github.com/pytorch/pytorch",
    repoDescription: "Tensors and Dynamic neural networks in Python with strong GPU acceleration.",
    framework: null,
  },
  {
    lines: [
      "export const createStore = <S>(initial: S) => {",
      "  let state = initial;",
      "  const listeners = new Set<() => void>();",
      "  return {",
      "    getState: () => state,",
      "    setState: (partial: Partial<S>) => {",
      "      state = { ...state, ...partial };",
      "      listeners.forEach((l) => l());",
      "    },",
      "    subscribe: (fn: () => void) => { listeners.add(fn); return () => listeners.delete(fn); },",
      "  };",
      "};",
    ],
    language: "TypeScript",
    repoName: "pmndrs/zustand",
    repoUrl: "https://github.com/pmndrs/zustand",
    repoDescription: "Bear necessities for state management in React.",
    framework: null,
  },
  {
    lines: [
      "fn process(items: &[Item]) -> Result<Vec<Output>, Error> {",
      "    items",
      "        .iter()",
      "        .filter(|i| i.enabled)",
      "        .map(|i| i.transform())",
      "        .collect::<Result<Vec<_>, _>>()",
      "}",
    ],
    language: "Rust",
    repoName: "rust-lang/rust",
    repoUrl: "https://github.com/rust-lang/rust",
    repoDescription: "Empowering everyone to build reliable and efficient software.",
    framework: null,
  },
  {
    lines: [
      "class UsersController < ApplicationController",
      "  def index",
      "    @users = User.page(params[:page]).per(25)",
      "    respond_to do |format|",
      "      format.html",
      "      format.json { render json: @users }",
      "    end",
      "  end",
      "end",
    ],
    language: "Ruby",
    repoName: "discourse/discourse",
    repoUrl: "https://github.com/discourse/discourse",
    repoDescription: "A platform for community discussion.",
    framework: null,
  },
  {
    lines: [
      "@Entity",
      "@Table(name = \"orders\")",
      "public class Order {",
      "    @Id @GeneratedValue",
      "    private Long id;",
      "    @ManyToOne(fetch = FetchType.LAZY)",
      "    private Customer customer;",
      "    @OneToMany(mappedBy = \"order\", cascade = CascadeType.ALL)",
      "    private List<OrderLine> lines = new ArrayList<>();",
      "}",
    ],
    language: "Java",
    repoName: "hibernate/hibernate-orm",
    repoUrl: "https://github.com/hibernate/hibernate-orm",
    repoDescription: "Hibernate ORM enables development of persistent domain models.",
    framework: null,
  },
  {
    lines: [
      "module App",
      "  class Service",
      "    def call(input)",
      "      Success(process(input))",
      "    rescue StandardError => e",
      "      Failure(e.message)",
      "    end",
      "  end",
      "end",
    ],
    language: "Ruby",
    repoName: "dry-rb/dry-monads",
    repoUrl: "https://github.com/dry-rb/dry-monads",
    repoDescription: "Common monads for Ruby.",
    framework: null,
  },
  {
    lines: [
      "async function fetchWithRetry(url: string, retries = 3): Promise<Response> {",
      "  for (let i = 0; i < retries; i++) {",
      "    try {",
      "      const res = await fetch(url);",
      "      if (res.ok) return res;",
      "    } catch (e) {",
      "      if (i === retries - 1) throw e;",
      "    }",
      "    await new Promise((r) => setTimeout(r, 200 * (i + 1)));",
      "  }",
      "  throw new Error('Failed after retries');",
      "}",
    ],
    language: "TypeScript",
    repoName: "microsoft/TypeScript",
    repoUrl: "https://github.com/microsoft/TypeScript",
    repoDescription: "TypeScript is a superset of JavaScript that compiles to clean JS.",
    framework: null,
  },
  {
    lines: [
      "function App() {",
      "  const [count, setCount] = useState(0);",
      "  return (",
      "    <main>",
      "      <h1>{count}</h1>",
      "      <button onClick={() => setCount((c) => c + 1)}>Increment</button>",
      "    </main>",
      "  );",
      "}",
    ],
    language: "JavaScript",
    repoName: "vitejs/vite",
    repoUrl: "https://github.com/vitejs/vite",
    repoDescription: "Next generation frontend tooling.",
    framework: null,
  },
  {
    lines: [
      "SELECT u.id, u.name, COUNT(o.id) AS order_count",
      "FROM users u",
      "LEFT JOIN orders o ON o.user_id = u.id",
      "WHERE u.created_at > NOW() - INTERVAL '30 days'",
      "GROUP BY u.id, u.name",
      "HAVING COUNT(o.id) > 0",
      "ORDER BY order_count DESC",
      "LIMIT 100;",
    ],
    language: "Python",
    repoName: "sqlalchemy/sqlalchemy",
    repoUrl: "https://github.com/sqlalchemy/sqlalchemy",
    repoDescription: "The Database Toolkit for Python.",
    framework: null,
  },
  {
    lines: [
      "namespace MyApp.Services",
      "{",
      "    public interface IEmailSender",
      "    {",
      "        Task SendAsync(string to, string subject, string body);",
      "    }",
      "}",
    ],
    language: "C#",
    repoName: "dotnet/runtime",
    repoUrl: "https://github.com/dotnet/runtime",
    repoDescription: ".NET is a cross-platform runtime for cloud, mobile, desktop, and IoT apps.",
    framework: null,
  },
  {
    lines: [
      "#include <vector>",
      "#include <algorithm>",
      "",
      "template<typename T>",
      "T clamp(const T& val, const T& lo, const T& hi) {",
      "    return std::min(hi, std::max(lo, val));",
      "}",
    ],
    language: "C++",
    repoName: "llvm/llvm-project",
    repoUrl: "https://github.com/llvm/llvm-project",
    repoDescription: "The LLVM Project is a collection of modular compiler technologies.",
    framework: null,
  },
  {
    lines: [
      "package main",
      "",
      "import (",
      "    \"encoding/json\"",
      "    \"net/http\"",
      ")",
      "",
      "func main() {",
      "    http.HandleFunc(\"/health\", func(w http.ResponseWriter, r *http.Request) {",
      "        json.NewEncoder(w).Encode(map[string]string{\"status\": \"ok\"})",
      "    })",
      "    http.ListenAndServe(\":8080\", nil)",
      "}",
    ],
    language: "Go",
    repoName: "kubernetes/kubernetes",
    repoUrl: "https://github.com/kubernetes/kubernetes",
    repoDescription: "Production-Grade Container Scheduling and Management.",
    framework: null,
  },
  {
    lines: [
      "from django.http import JsonResponse",
      "from django.views import View",
      "",
      "class HealthView(View):",
      "    def get(self, request):",
      "        return JsonResponse({\"status\": \"ok\"})",
    ],
    language: "Python",
    repoName: "django/django",
    repoUrl: "https://github.com/django/django",
    repoDescription: "The Web framework for perfectionists with deadlines.",
    framework: "Django",
  },
  {
    lines: [
      "use actix_web::{get, web, App, HttpServer, Responder};",
      "",
      "#[get(\"/\")]",
      "async fn index() -> impl Responder {",
      "    \"Hello world!\"",
      "}",
      "",
      "#[actix_web::main]",
      "async fn main() -> std::io::Result<()> {",
      "    HttpServer::new(|| App::new().service(index))",
      "        .bind((\"127.0.0.1\", 8080))?",
      "        .run()",
      "        .await",
      "}",
    ],
    language: "Rust",
    repoName: "actix/actix-web",
    repoUrl: "https://github.com/actix/actix-web",
    repoDescription: "Actix Web is a powerful, pragmatic, and extremely fast web framework for Rust.",
    framework: "Actix",
  },
  {
    lines: [
      "const express = require('express');",
      "const app = express();",
      "app.use(express.json());",
      "app.get('/api/items', async (req, res) => {",
      "  const items = await db.items.findMany();",
      "  res.json({ items });",
      "});",
      "app.listen(3000);",
    ],
    language: "JavaScript",
    repoName: "expressjs/express",
    repoUrl: "https://github.com/expressjs/express",
    repoDescription: "Fast, unopinionated, minimalist web framework for Node.",
    framework: "Express",
  },
  {
    lines: [
      "enum Status { Pending, Active, Done }",
      "",
      "struct Task {",
      "    id: u64,",
      "    title: String,",
      "    status: Status,",
      "}",
      "",
      "impl Task {",
      "    fn complete(mut self) -> Self {",
      "        self.status = Status::Done;",
      "        self",
      "    }",
      "}",
    ],
    language: "Rust",
    repoName: "serde-rs/serde",
    repoUrl: "https://github.com/serde-rs/serde",
    repoDescription: "Serialization framework for Rust.",
    framework: null,
  },
  {
    lines: [
      "public class BinarySearch {",
      "    public static int search(int[] arr, int target) {",
      "        int lo = 0, hi = arr.length - 1;",
      "        while (lo <= hi) {",
      "            int mid = lo + (hi - lo) / 2;",
      "            if (arr[mid] == target) return mid;",
      "            if (arr[mid] < target) lo = mid + 1;",
      "            else hi = mid - 1;",
      "        }",
      "        return -1;",
      "    }",
      "}",
    ],
    language: "Java",
    repoName: "apache/kafka",
    repoUrl: "https://github.com/apache/kafka",
    repoDescription: "Mirror of Apache Kafka.",
    framework: null,
  },
];
